export const Assets = {
  icons: {
    logo: "/assets/icons/logo.png",
  },
  images: {
    heroBg: "/assets/images/hero_bg_img.png",
    heroBg1: "/assets/images/hero_bg_img_1.png",
    heroBg2: "/assets/images/hero_bg_img_2.png",
    heroBg3: "/assets/images/hero_bg_img_3.png",
    whyJoin: "/assets/images/ttt.jpg",
    upcomingEvent: "/assets/images/upcoming_event_img.jpg",
    border: "/assets/images/Border.png",
    partners: "/assets/images/parttners.png",
    chipsBg: "/assets/images/chips_bg_img.png",
    careerPathwaysBg: "/assets/images/career_pathways_bg_img.png",
    atAGlanceBg: "/assets/images/at_a_glance_bg_img.png",
    membershipCardBg: "/assets/images/membership_catigory_card.png",
    certificateCardBg: "/assets/images/certificate_bg.png",
    footerPattern: "/assets/images/footer_bg_parttern.png",
    footerLogo: "/assets/images/chips_logo_faded_logo.png.png",
    partnerLogos: {
      p1: "/assets/images/p1.png",
      p2: "/assets/images/p2.png",
      p3: "/assets/images/p3.png",
      p4: "/assets/images/p4.png",
      p5: "/assets/images/p5.png",
      p6: "/assets/images/p6.png",
    },
    membership: {
      student: "/assets/images/student-membership.png",
      affiliate: "/assets/images/affliate-membership.png",
      licentiate: "/assets/images/licentiate.png",
      associate: "/assets/images/associate.png",
      certified: "/assets/images/certified.png",
    },
    certificates: {
      bclp: "/assets/images/BCLP.png",
      clpa: "/assets/images/CLPA.png",
      clpo: "/assets/images/CLPO.png",
      clpm: "/assets/images/CLPM.png",
      acipm: "/assets/images/ACIPM.png",
      chlps: "/assets/images/CHLPS.png",
    },
  },
} as const;
