export const Assets = {
  icons: {
    logo: "/assets/icons/logo.png",
  },
  images: {
    heroBg: "/assets/images/hero_bg_img.png",
    heroBg1: "/assets/images/hero-bg-1.webp",
    heroBg2: "/assets/images/hero-bg-2.webp",
    heroBg3: "/assets/images/hero-bg-3.webp",
    aboutHeroBg: "/assets/images/about_us_hero_bg.png",
    ourStoryBg: "/assets/images/our_story_bg_img.png",
    ourStory: "/assets/images/our_story_left_img.png",
    howWeAreGoverned: "/assets/images/how_we_are_governed.jpg",
    leadership: {
      victoriaOgbuehi: "/assets/images/victoria_ogbuehi.png",
      josephOkpotu: "/assets/images/joseph_okpotu.png",
      adegbengaKoko: "/assets/images/adegbenga_koko.png",
    },
    whyJoin: "/assets/images/ttt.jpg",
    whoShouldJoin:
      "/assets/images/Professional working with colleagues in a modern office.png",
    upcomingEvent: "/assets/images/upcoming_event_img.jpg",
    border: "/assets/images/Border.png",
    partners: "/assets/images/parttners.png",
    partnersBg: "/assets/images/parttern_bg_img.png",
    chipsBg: "/assets/images/chips_bg_img.png",
    careerPathwaysBg: "/assets/images/Section 1.png",
    atAGlanceBg: "/assets/images/at_a_glance_bg_img.png",
    membershipCardBg: "/assets/images/membership_catigory_card.png",
    certificateCardBg: "/assets/images/Link 1.png",
    certificationHero: "/assets/images/certification_hero.png",
    eventHero: "/assets/images/event_hero_bg.png",
    eventDetailsHero: "/assets/images/event_details_page_hero_bg.png",
    newsHero: "/assets/images/new_and_blog_hero_bg.png",
    cardPatternLeft: "/assets/images/left_bg_parttern.png",
    cardPatternRight: "/assets/images/right_bg_parttern.png",
    events: {
      liveForum: "/assets/images/ttt.jpg",
      webinar:
        "/assets/images/Professional working in a modern office environment.png",
      seminar:
        "/assets/images/Professional working with colleagues in a modern office.png",
      conference: "/assets/images/upcoming_event_img.jpg",
      career: "/assets/images/our_story_left_img.png",
      compliance: "/assets/images/why_join_chips.jpg",
      operations: "/assets/images/how_we_are_governed.jpg",
    },
    certificationMatters:
      "/assets/images/Professional working in a modern office environment.png",
    checkGold: "/assets/images/check_gold.png",
    supportSectionBg: "/assets/images/bg_parttern.png",
    footerPattern: "/assets/images/footer_bg_parttern.png",
    footerBg: "/assets/images/footer_bg_img.png",
    footerLogo: "/assets/images/chips_logo_faded_logo.png.png",
    fullLogo: "/assets/images/chips-ful-logo-1.png",
    partnerLogos: {
      p1: "/assets/images/p1.png",
      p2: "/assets/images/p2.png",
      p3: "/assets/images/p3.png",
      p4: "/assets/images/p4.png",
      p5: "/assets/images/p5.png",
      p6: "/assets/images/p6.png",
    },
    membership: {
      student: "/assets/images/student-membership.png",
      affiliate: "/assets/images/affliate-membership.png",
      licentiate: "/assets/images/licentiate.png",
      associate: "/assets/images/associate.png",
      certified: "/assets/images/certified.png",
    },
    certificates: {
      bclp: "/assets/images/BCLP.png",
      clpa: "/assets/images/CLPA.png",
      clpo: "/assets/images/CLPO.png",
      clpm: "/assets/images/CLPM.png",
      acipm: "/assets/images/ACIPM.png",
      chlps: "/assets/images/CHLPS.png",
    },
  },
} as const;
